myblog/models.py
import datetime
from typing import Dict, List, Optional

from flask_login import UserMixin  # type: ignore
from sqlalchemy import ForeignKey, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from typing_extensions import Annotated
from werkzeug.security import check_password_hash, generate_password_hash

from myblog.core.ext import db

"""设置类型映射"""

intpk = Annotated[int, mapped_column(primary_key=True)]
timestamp = Annotated[
    datetime.datetime,
    mapped_column(nullable=False, server_default=func.current_timestamp()),
]


class BaseModel(db.Model):  # type: ignore
    """声明基类，用于公共模型, 以及公共查询"""

    __abstract__ = True

    id: Mapped[intpk]
    created_at: Mapped[timestamp]

    @classmethod
    def save(cls, data: Dict):
        new_data = cls(**data)
        db.session.add(new_data)
        try:
            db.session.commit()
        except Exception:
            db.session.rollback()

    def update(self, data: Dict) -> None:
        if data:
            fields = [x for x in self.__dict__.keys() if not x.startswith("_")]
            for k, v in data.items():
                if k not in fields:
                    print(f"WARN: Field `{k}` may not be saved!")
                else:
                    if k == "password":
                        v = generate_password_hash(v)
                    setattr(self, k, v)
            try:
                db.session.commit()
            except Exception:
                db.session.rollback()


class Admin(BaseModel, UserMixin):
    __tablename__ = "admin"

    username: Mapped[str] = mapped_column(String(20))
    password_hash: Mapped[str] = mapped_column(String(256))
    blog_title: Mapped[str] = mapped_column(String(60))
    blog_sub_title: Mapped[str] = mapped_column(String(100))
    name: Mapped[str] = mapped_column(String(30))
    about: Mapped[str] = mapped_column(Text)
    custom_footer: Mapped[Optional[str]] = mapped_column(Text)
    custom_css: Mapped[Optional[str]] = mapped_column(Text)
    custom_js: Mapped[Optional[str]] = mapped_column(Text)

    def __repr__(self):
        return f"<Admin: {self.username}"

    @property
    def password(self):
        raise AttributeError("Write-only property")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def validate_password(self, password):
        return check_password_hash(self.password_hash, password)


class Category(BaseModel):
    __tablename__ = "category"

    name: Mapped[str] = mapped_column(String(30), unique=True)

    posts: Mapped[List["Post"]] = relationship(back_populates="category")


class Post(BaseModel):
    __tablename__ = "post"

    title: Mapped[str] = mapped_column(String(60))
    body: Mapped[str] = mapped_column(Text)
    updated_at: Mapped[Optional[datetime.datetime]] = mapped_column(
        onupdate=lambda: datetime.datetime.now(datetime.timezone.utc)
    )
    can_comment: Mapped[bool] = mapped_column(default=True)

    category_id: Mapped[int] = mapped_column(ForeignKey("category.id"))

    category: Mapped["Category"] = relationship(back_populates="posts")

    comments: Mapped[List["Comment"]] = relationship(
        back_populates="post", cascade="all, delete-orphan"
    )


class Comment(BaseModel):
    __tablename__ = "comment"

    author: Mapped[str] = mapped_column(String(30))
    email: Mapped[str] = mapped_column(String(255))
    site: Mapped[Optional[str]] = mapped_column(String(255))
    body: Mapped[str] = mapped_column(Text)
    from_admin: Mapped[bool] = mapped_column(default=False)
    reviewed: Mapped[bool] = mapped_column(default=False)

    post_id: Mapped[int] = mapped_column(ForeignKey("post.id"))
    post: Mapped["Post"] = relationship(back_populates="comments")

    replied_id: Mapped[Optional[int]] = mapped_column(ForeignKey("comment.id"))
    replies: Mapped[List["Comment"]] = relationship(
        "Comment", back_populates="replied", cascade="all, delete-orphan"
    )
    replied: Mapped["Comment"] = relationship(
        "Comment", back_populates="replies", remote_side="Comment.id"
    )

myblog/forms.py
from flask_ckeditor import CKEditorField  # type: ignore
from flask_wtf import FlaskForm  # type: ignore
from sqlalchemy import select
from wtforms import (  # type: ignore
    BooleanField,
    HiddenField,
    PasswordField,
    SelectField,
    StringField,
    SubmitField,
    TextAreaField,
    ValidationError,
)
from wtforms.validators import (  # type: ignore
    URL,
    DataRequired,
    Email,
    Length,
    Optional,
)

from myblog.ext import db
from myblog.models import Category


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired(), Length(1, 20)])
    password = PasswordField("Password", validators=[DataRequired(), Length(8, 128)])
    remember = BooleanField("Remember me")
    submit = SubmitField("Log in")


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(1, 60)])
    category = SelectField("Category", coerce=int, default=1)
    body = CKEditorField("Body", validators=[DataRequired()])
    submit = SubmitField()

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.category.choices = [
            (category.id, category.name)
            for category in db.session.execute(
                select(Category).order_by(Category.name).all()
            )
        ]


class CategoryForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired(), Length(1, 30)])
    submit = SubmitField()

    def validate_name(self, field):
        if db.session.execute(
            select(Category).where(Category.name == field.data).first()
        ):
            raise ValidationError("Name already in use.")


class CommentForm(FlaskForm):
    author = StringField("Name", validators=[DataRequired(), Length(1, 30)])
    email = StringField("Email", validators=[DataRequired(), Email(), Length(1, 254)])
    site = StringField("Site", validators=[Optional(), URL(), Length(0, 255)])
    body = TextAreaField("Comment", validators=[DataRequired()])
    submit = SubmitField()


class AdminCommentForm(CommentForm):
    author = HiddenField()
    email = HiddenField()
    site = HiddenField()

myblog/__init__.py
__all__ = ["Post", "Admin", "Category", "Comment"]

from flask import Flask

from myblog.blueprints.admin import admin_bp
from myblog.blueprints.auth import auth_bp
from myblog.blueprints.blog import blog_bp
from myblog.core.commands import register_commands
from myblog.core.ext import bootstrap, ckeditor, csrf, db, login_manager, migrate
from myblog.core.templating import register_template_handlers
from myblog.models import Admin, Category, Comment, Post
from myblog.settings import config


def create_app(config_name: str = "dev"):
    # 创建 Flask 程序实例
    app = Flask(__name__)

    # 使用对象的方式引入配置文件
    app.config.from_object(config[config_name])

    # 注册蓝图
    app.register_blueprint(blog_bp)
    app.register_blueprint(auth_bp, url_prefix="/auth")
    app.register_blueprint(admin_bp, url_prefix="/admin")
    app.add_url_rule("/", endpoint="index")

    # 引入扩展
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)
    ckeditor.init_app(app)
    # mail.init_app(app)
    # toolbar.init_app(app)
    migrate.init_app(app, db)
    # register_logging(app)
    register_commands(app)
    # register_errors(app)
    register_template_handlers(app)
    # register_request_handlers(app)
    # register_shell_handlers(app)

    return app

myblog/blueprints/admin.py
from flask import Blueprint

admin_bp = Blueprint("admin", __name__)


@admin_bp.route("/post")
def manager_post(): ...

myblog/blueprints/auth.py
from flask import Blueprint

auth_bp = Blueprint("auth", __name__)


@auth_bp.route("/login")
def login(): ...

myblog/blueprints/blog.py
from flask import Blueprint, current_app, render_template, request
from sqlalchemy import select

from myblog.core.ext import db
from myblog.models import Post

blog_bp = Blueprint("blog", __name__)


@blog_bp.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config["POST_PER_PAGE"]
    pagination = db.paginate(
        select(Post).order_by(Post.created_at.desc()), page=page, per_page=per_page
    )
    posts = pagination.items
    return render_template("blog/index.html", pagination=pagination, posts=posts)

myblog/templates/base.html
{% from 'bootstrap4/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} - {{admin.blog_title|default('Blog Title')}} </title>
    <link rel="icon" href="{{url_for('static', filename='favicon')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'perfect_blue'))}}" type="text/css">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}" type="text/css">
    {% endblock head %}
</head>
<body>
{% block nav %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('blog.index') }}" >{{ admin.blog_title }}</a>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                {{ render_nav_item('blog.index', 'Home') }}
                {{ render_nav_item('blog.about', 'About') }}
            </ul>
        </div>
    </div>
</nav>

{% endblock nav %}

<main class="container">
    {% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{message[0]}}" role="alert">
        <button type="button" class="close" data-dimiss="alert">&items;</button>
        {{ message[1]}}
    </div>
    {% endfor %}
    {%block content %} {% endblock content%}
    {% block footer %}
    <footer>
        <p class="float-left">
            <small> &copy; 2018 <a href="http://greyli.com" title="Written by Grey Li">Grey Li</a> -
                <a href="https://github.com/greyli/bluelog" title="Fork me on GitHub">GitHub</a> -
                <a href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
            </small>
        </p>
    </footer>
    {%endblock footer %}

</main>

{% block script %}
<script type="text/javascript" src="{{url_for('static', filename='js/jquery-3.2.1.slim.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='js/popper.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{url_for('static', filename='js/script.js')}}"></script>
{{ moment.include_moment(local_js=url_for('static', filename="js/moment-with-locales.min.js"))}}

{% endblock %}
</body>
</html>

myblog/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=post.id) }}">{{ post.title }}</a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_post', post_id=post.id) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.created_at).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No posts yet.</h5>
    </div>
{% endif %}

myblog/templates/blog/_sidebar.html
{% if links %}
<div class="card mb-3">
  <div class="card-header">Links</div>
  <ul class="list-group list-group-flush">
    {% for link in links %}
    <li
      class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"
    >
      <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %} {% if categories %}
<div class="card mb-3">
  <div class="card-header">Categories</div>
  <ul class="list-group list-group-flush">
    {% for category in categories %}
    <li
      class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"
    >
      <a href="{{ url_for('blog.show_category', category_id=category.id) }}">
        {{ category.name }}
      </a>
      <span class="badge badge-primary badge-pill">
        {{ category.posts|length }}</span
      >
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}

<div class="dropdown">
  <button
    class="btn btn-default dropdown-toggle"
    type="button"
    id="dropdownMenuButton"
    data-toggle="dropdown"
    aria-haspopup="true"
    aria-expanded="false"
  >
    Change Theme
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% for theme_name, display_name in config.BLOG_THEMES.items() %}
    <a
      class="dropdown-item"
      href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}"
    >
      {{ display_name }}</a
    >
    {% endfor %}
  </div>
</div>

myblog/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pager %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="page-header">
    <h1 class="display-3">{{admin.blog_title|default('Blog Title')}}</h1>
    <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle')}}</h4>
</div>

<div class="row">
    <div class="col-sm-8">
        {% include 'blog/_posts.html' %}
        {% if posts %}
            <div class="page-footer">{{ render_pager(pagination) }}</div>
        {% endif %}
    </div>

</div>


{% endblock %}

myblog/templates/blog/post.html
{% extends 'base.html' %} {% block title %}{{post.title}} {% endblock %} {%
block content %}
<div class="page-header">
  <h1>{{post.title}}</h1>
  <small>
    Category:
    <a href="{{url_for('.show_category', category_id=post.category.id)}}">
      {{ post.category.name}} </a
    ><br />
    Date: {{ moment(post.created_at).format('LL')}}
  </small>
</div>
<div class="row">
  <div class="col-sm-8">
    {{post.body|safe}}
    <div class="comments" id="comments">...</div>
  </div>

  <div class="col-sm-4 sidebar">{% include "blog/_sidebar.html" %}</div>
</div>

{% endblock%}